#!/bin/bash 

# location of the config file
config="$HOME/.config/ceu/config"

# tries to load the config file
if [ -f "$config" ]; then
    source "$config"
else
    echo "$config is not a file!"
    exit 1
fi

# removes the current encrypted file
if [ -f "$target" ]; then
    rm "$target";
fi

# compresses the target folder and pipes its output to gpg for encryption
cd "$source"
GZIP_OPT=-9 tar $(
    for i in "${exclude[@]}"; do
        echo --exclude="$i";
    done
) -cz . | gpg --output "$target" --recipient "$gpgid" --encrypt
cd "$OLDPWD"

# tar -cz your_dir | gpg -c -o your_archive.tgz.gpg
# gpg -d your_archive.tgz.gpg | tar xz