#!/bin/bash 

# location of the config file
config="./config"

# tries to load the config file
if [ -f "$config" ]; then
    source "$config"
else
    echo "$config is not a file!"
    exit 1
fi

# removes the current compressed file
if [ -f "$target".tar.gz ]; then
    rm "$target".tar.gz;
fi

# compresses the target folder
cd "$source"
GZIP_OPT=-9 tar $(
    for i in "${exclude[@]}"; do
        echo --exclude="$i";
    done
) -czf "$target".tar.gz .
cd "$OLDPWD"
