#!/bin/bash

# gpg email
gpgid="email@domain.com"

# dirs used and excluded files/folders
source="/path/to/source" # is a folder
target="/path/to/target" # is a file
exclude=('ignorehiddenfilesinthisfolder/.*' 'ignorethisfolderorfile' 'also/ignore/thisfolderorfile') # these inside $source are ignored, notice the lack of '/' at the start of the strings and the use of single quotes (tar --exclude= format) - if source is $HOME and you want to use '.*' as an exclude, change it to '.[^/]*', for other directories you can use '.*' normally


# remote location to send the encrypted file
remote="remotename:/remotefolder/remotefile" # rclone format

# prevents running with default configs
# you can remove them if you want but make sure you changed the placeholder values in this file with the ones you want
if [[ 
    "$gpgid" == "email@domain.com" ||
    "$source" == "/path/to/source" ||
    "$target" == "/path/to/target" ||
    "${exclude[@]}" == 'ignorehiddenfilesinthisfolder/.* ignorethisfolderorfile also/ignore/thisfolderorfile' ||
    "$remote" == "remotename:/remotefolder/remotefile"
]]; then
    echo "You must edit the config file before running"
    exit 1
fi
